-- Script de datos iniciales para GestiApar
-- Ejecutar en Oracle como el usuario GESTIAPAR2 (o el usuario propietario del esquema)
-- Verificar primero si ya existen datos antes de insertar

-- ── TIPOPERSONA ──────────────────────────────────────────────
-- Insertar solo si la tabla está vacía
INSERT INTO TIPOPERSONA (IDTIPOPERSONA, DESCRIPCION)
  SELECT 1, 'Cliente'
  FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM TIPOPERSONA WHERE IDTIPOPERSONA = 1);

INSERT INTO TIPOPERSONA (IDTIPOPERSONA, DESCRIPCION)
  SELECT 2, 'Empleado'
  FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM TIPOPERSONA WHERE IDTIPOPERSONA = 2);

INSERT INTO TIPOPERSONA (IDTIPOPERSONA, DESCRIPCION)
  SELECT 3, 'Propietario'
  FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM TIPOPERSONA WHERE IDTIPOPERSONA = 3);

-- ── PERFIL ───────────────────────────────────────────────────
INSERT INTO PERFIL (IDPERFIL, NOMBRE)
  SELECT 1, 'Administrador'
  FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM PERFIL WHERE IDPERFIL = 1);

INSERT INTO PERFIL (IDPERFIL, NOMBRE)
  SELECT 2, 'Empleado'
  FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM PERFIL WHERE IDPERFIL = 2);

INSERT INTO PERFIL (IDPERFIL, NOMBRE)
  SELECT 3, 'Cliente'
  FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM PERFIL WHERE IDPERFIL = 3);

COMMIT;
